### ISSUE TITLE
Merge with sthbrx-blog project

### ISSUE THREAD

**Issue by Aerijo** [sthbrx/sthbrx.github.io-old#8]
(It's Ben on my day off)

It is unnecessary to have a separate project for the blog source. The two projects can be merged into this one by renaming the current `master` branch to `gh-pages`, and resetting the `master` branch to the `master` branch of `sthbrx-blog`. No loss of history, just shuffling branches (though clones will need to be manually fixed, especially if there is local un-pushed work).

This helps :fire: the `output` submodule, making it an ignored folder and 'publishing' to the `gh-pages` branch instead (Pelican generated Makefile supports this, see `make github` in https://github.com/Aerijo/sthbrx.github.io/tree/regen-config 

Example here https://github.com/Aerijo/sthbrx.github.io

**Comment by ajdlinux** [comment]
You should enjoy other things on your day off
